input {
  file {
    path => "/workspace/logs/medusa-json.log"
    start_position => "beginning"
    sincedb_path => "/dev/null"
    codec => "json"
    tags => ["medusa"]
  }
}

filter {
  mutate {
    remove_field => ["@version", "host", "log", "event", "message"]
  }
}

output {
  elasticsearch {
    hosts => ["http://elasticsearch:9200"]
    index => "behavior-logs-%{+YYYY.MM.dd}"
  }
}
